# Generated by Django 3.0.1 on 2020-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank='x.img', upload_to='pharmacy_pics'),
        ),
    ]
